## Load and print dataset

In [141]:
#import the pandas library
import pandas as pd
#Load the data set
df=pd.read_csv("house_data.csv")
#Print dataset
print(df)

        Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg
1        2          20       RL         80.0     9600   Pave   NaN      Reg
2        3          60       RL         68.0    11250   Pave   NaN      IR1
3        4          70       RL         60.0     9550   Pave   NaN      IR1
4        5          60       RL         84.0    14260   Pave   NaN      IR1
...    ...         ...      ...          ...      ...    ...   ...      ...
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0
...          ...       ...  ...      ...    ...    ...         ...     ...
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0

     MoSold YrSold  SaleType  SaleCondition  SalePrice
0         2   2008        WD         Normal     208500
1         5   2007        WD         Normal     181500
2         9   2008        WD         Normal     223500
3         2   2006        WD        Abnorml     140000
4        12   2008        WD         Normal     250000
...     ...    ...       ...            ...        ...
1455      8   2007        WD         Normal     175000
1456      2   2010        WD         Normal     210000
1457      5   2010        WD         Normal     266500
1458      4   2010        WD         Normal     142125
1459      6   2008        WD         Normal     147500

[1460 rows x 81 columns]

## shape of dataset

In [143]:
#Check the shape of data
df.shape

(1460, 81)

## Print information related given data

In [145]:
#Check information to check the null values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

## Print names of columns

In [147]:
#Print the columns names to check the number of columns
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

## Find null values containing columns with isna()

In [9]:
#Check the null values
df.isna()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,False,False,False,False,False,False,True,False,False,False,...,False,True,True,True,False,False,False,False,False,False
1,False,False,False,False,False,False,True,False,False,False,...,False,True,True,True,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False,False,False,...,False,True,True,True,False,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False,...,False,True,True,True,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,...,False,True,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,False,False,False,False,False,False,True,False,False,False,...,False,True,True,True,False,False,False,False,False,False
1456,False,False,False,False,False,False,True,False,False,False,...,False,True,False,True,False,False,False,False,False,False
1457,False,False,False,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
1458,False,False,False,False,False,False,True,False,False,False,...,False,True,True,True,False,False,False,False,False,False
1459,False,False,False,False,False,False,True,False,False,False,...,False,True,True,True,False,False,False,False,False,False

In [149]:
#check the null values
df.isna().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [151]:
#Total null values in whole dataset
df.isna().sum().sum()

7829

In [35]:
#check shape for starting to clean the data
df.shape

(1460, 81)

In [37]:
#info check
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [153]:
#Drop the columns which has too much null values
df=df.drop(['Alley','MasVnrType','FireplaceQu','PoolQC','Fence','MiscFeature',], axis= 1)

In [155]:
#Fill the null values with mean or median
df['LotFrontage']=df['LotFrontage'].interpolate()
df['MasVnrArea']=df['LotFrontage'].interpolate()

In [157]:
#Now check that null columns has deleted
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 75 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   LotShape       1460 non-null   object
 7   LandContour    1460 non-null   object
 8   Utilities      1460 non-null   object
 9   LotConfig      1460 non-null   object
 10  LandSlope      1460 non-null   object
 11  Neighborhood   1460 non-null   object
 12  Condition1     1460 non-null   object
 13  Condition2     1460 non-null   object
 14  BldgType       1460 non-null   object
 15  HouseStyle     1460 non-null   object
 16  OverallQual    1460 non-null   int64
 17  OverallCond    1460 non-null   int64
 18  YearBuilt      1460 non-null   int64
 19  YearRemodAdd   1460 non-null   int64
 20  RoofStyle      1460 non-null   object
 21  RoofMatl       1460 non-null   object
 22  Exterior1st    1460 non-null   object
 23  Exterior2nd    1460 non-null   object
 24  MasVnrArea     1460 non-null   float64
 25  ExterQual      1460 non-null   object
 26  ExterCond      1460 non-null   object
 27  Foundation     1460 non-null   object
 28  BsmtQual       1423 non-null   object
 29  BsmtCond       1423 non-null   object
 30  BsmtExposure   1422 non-null   object
 31  BsmtFinType1   1423 non-null   object
 32  BsmtFinSF1     1460 non-null   int64
 33  BsmtFinType2   1422 non-null   object
 34  BsmtFinSF2     1460 non-null   int64
 35  BsmtUnfSF      1460 non-null   int64
 36  TotalBsmtSF    1460 non-null   int64
 37  Heating        1460 non-null   object
 38  HeatingQC      1460 non-null   object
 39  CentralAir     1460 non-null   object
 40  Electrical     1459 non-null   object
 41  1stFlrSF       1460 non-null   int64
 42  2ndFlrSF       1460 non-null   int64
 43  LowQualFinSF   1460 non-null   int64
 44  GrLivArea      1460 non-null   int64
 45  BsmtFullBath   1460 non-null   int64
 46  BsmtHalfBath   1460 non-null   int64
 47  FullBath       1460 non-null   int64
 48  HalfBath       1460 non-null   int64
 49  BedroomAbvGr   1460 non-null   int64
 50  KitchenAbvGr   1460 non-null   int64
 51  KitchenQual    1460 non-null   object
 52  TotRmsAbvGrd   1460 non-null   int64
 53  Functional     1460 non-null   object
 54  Fireplaces     1460 non-null   int64
 55  GarageType     1379 non-null   object
 56  GarageYrBlt    1379 non-null   float64
 57  GarageFinish   1379 non-null   object
 58  GarageCars     1460 non-null   int64
 59  GarageArea     1460 non-null   int64
 60  GarageQual     1379 non-null   object
 61  GarageCond     1379 non-null   object
 62  PavedDrive     1460 non-null   object
 63  WoodDeckSF     1460 non-null   int64
 64  OpenPorchSF    1460 non-null   int64
 65  EnclosedPorch  1460 non-null   int64
 66  3SsnPorch      1460 non-null   int64
 67  ScreenPorch    1460 non-null   int64
 68  PoolArea       1460 non-null   int64
 69  MiscVal        1460 non-null   int64
 70  MoSold         1460 non-null   int64
 71  YrSold         1460 non-null   int64
 72  SaleType       1460 non-null   object
 73  SaleCondition  1460 non-null   object
 74  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(37)
memory usage: 855.6+ KB

In [159]:
#check the null values sum of first 40 columns To make sure that null values has been removed
df.isnull().sum().head(40)

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
Street           0
LotShape         0
LandContour      0
Utilities        0
LotConfig        0
LandSlope        0
Neighborhood     0
Condition1       0
Condition2       0
BldgType         0
HouseStyle       0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
RoofStyle        0
RoofMatl         0
Exterior1st      0
Exterior2nd      0
MasVnrArea       0
ExterQual        0
ExterCond        0
Foundation       0
BsmtQual        37
BsmtCond        37
BsmtExposure    38
BsmtFinType1    37
BsmtFinSF1       0
BsmtFinType2    38
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
Heating          0
HeatingQC        0
CentralAir       0
dtype: int64

In [161]:
#Drop the rows of specific columns that have null values
df=df.dropna(subset=['BsmtQual', 'BsmtCond', 
'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Electrical', 'GarageType', 
'GarageYrBlt', 'GarageFinish', 'GarageQual', 'GarageCond'],axis=0)

In [163]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1346 entries, 0 to 1459
Data columns (total 75 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1346 non-null   int64
 1   MSSubClass     1346 non-null   int64
 2   MSZoning       1346 non-null   object
 3   LotFrontage    1346 non-null   float64
 4   LotArea        1346 non-null   int64
 5   Street         1346 non-null   object
 6   LotShape       1346 non-null   object
 7   LandContour    1346 non-null   object
 8   Utilities      1346 non-null   object
 9   LotConfig      1346 non-null   object
 10  LandSlope      1346 non-null   object
 11  Neighborhood   1346 non-null   object
 12  Condition1     1346 non-null   object
 13  Condition2     1346 non-null   object
 14  BldgType       1346 non-null   object
 15  HouseStyle     1346 non-null   object
 16  OverallQual    1346 non-null   int64
 17  OverallCond    1346 non-null   int64
 18  YearBuilt      1346 non-null   int64
 19  YearRemodAdd   1346 non-null   int64
 20  RoofStyle      1346 non-null   object
 21  RoofMatl       1346 non-null   object
 22  Exterior1st    1346 non-null   object
 23  Exterior2nd    1346 non-null   object
 24  MasVnrArea     1346 non-null   float64
 25  ExterQual      1346 non-null   object
 26  ExterCond      1346 non-null   object
 27  Foundation     1346 non-null   object
 28  BsmtQual       1346 non-null   object
 29  BsmtCond       1346 non-null   object
 30  BsmtExposure   1346 non-null   object
 31  BsmtFinType1   1346 non-null   object
 32  BsmtFinSF1     1346 non-null   int64
 33  BsmtFinType2   1346 non-null   object
 34  BsmtFinSF2     1346 non-null   int64
 35  BsmtUnfSF      1346 non-null   int64
 36  TotalBsmtSF    1346 non-null   int64
 37  Heating        1346 non-null   object
 38  HeatingQC      1346 non-null   object
 39  CentralAir     1346 non-null   object
 40  Electrical     1346 non-null   object
 41  1stFlrSF       1346 non-null   int64
 42  2ndFlrSF       1346 non-null   int64
 43  LowQualFinSF   1346 non-null   int64
 44  GrLivArea      1346 non-null   int64
 45  BsmtFullBath   1346 non-null   int64
 46  BsmtHalfBath   1346 non-null   int64
 47  FullBath       1346 non-null   int64
 48  HalfBath       1346 non-null   int64
 49  BedroomAbvGr   1346 non-null   int64
 50  KitchenAbvGr   1346 non-null   int64
 51  KitchenQual    1346 non-null   object
 52  TotRmsAbvGrd   1346 non-null   int64
 53  Functional     1346 non-null   object
 54  Fireplaces     1346 non-null   int64
 55  GarageType     1346 non-null   object
 56  GarageYrBlt    1346 non-null   float64
 57  GarageFinish   1346 non-null   object
 58  GarageCars     1346 non-null   int64
 59  GarageArea     1346 non-null   int64
 60  GarageQual     1346 non-null   object
 61  GarageCond     1346 non-null   object
 62  PavedDrive     1346 non-null   object
 63  WoodDeckSF     1346 non-null   int64
 64  OpenPorchSF    1346 non-null   int64
 65  EnclosedPorch  1346 non-null   int64
 66  3SsnPorch      1346 non-null   int64
 67  ScreenPorch    1346 non-null   int64
 68  PoolArea       1346 non-null   int64
 69  MiscVal        1346 non-null   int64
 70  MoSold         1346 non-null   int64
 71  YrSold         1346 non-null   int64
 72  SaleType       1346 non-null   object
 73  SaleCondition  1346 non-null   object
 74  SalePrice      1346 non-null   int64
dtypes: float64(3), int64(35), object(37)
memory usage: 799.2+ KB

In [67]:
#to check how many columns have integer values
df.describe().head(20)

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1338.000000,1338.000000,1338.000000,1338.000000,1338.000000,1338.000000,1338.000000,1338.000000,1338.000000,1338.000000,...,1338.000000,1338.000000,1338.000000,1338.000000,1338.00000,1338.000000,1338.000000,1338.000000,1338.000000,1338.000000
mean,731.228700,56.136024,70.785750,10706.294469,6.219731,5.596413,1973.029148,1985.668909,110.360239,464.234679,...,99.384903,47.782511,21.263827,3.585949,16.43423,3.010463,42.932735,6.331839,2007.805680,186761.782511
std,421.779691,41.252576,23.223957,10336.621126,1.324472,1.078124,29.563540,20.296463,185.604816,458.792420,...,127.537065,65.362562,60.843964,30.224622,58.05159,41.961337,508.056255,2.699437,1.330691,78913.847668
min,1.000000,20.000000,21.000000,1300.000000,2.000000,2.000000,1880.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,1.000000,2006.000000,35311.000000
25%,366.250000,20.000000,60.000000,7744.000000,5.000000,5.000000,1956.000000,1968.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,5.000000,2007.000000,135000.000000
50%,730.500000,50.000000,70.000000,9600.000000,6.000000,5.000000,1976.000000,1994.500000,0.000000,413.000000,...,6.000000,28.000000,0.000000,0.000000,0.00000,0.000000,0.000000,6.000000,2008.000000,168500.000000
75%,1098.750000,70.000000,80.000000,11760.750000,7.000000,6.000000,2001.000000,2004.000000,174.000000,733.000000,...,174.500000,70.000000,0.000000,0.000000,0.00000,0.000000,0.000000,8.000000,2009.000000,220000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.00000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [165]:
#Again check the shape
df.shape

(1346, 75)

In [167]:
#Drop undesired column of id
df=df.drop('Id',axis=1)

In [169]:
#To check that all the null values have been removed
df.isnull().sum().sum()

0

In [171]:
#Check final shape
df.shape

(1346, 74)

In [173]:
#Check the categories of data in column
df['Condition1'].value_counts()

Condition1
Norm      1170
Feedr       63
Artery      43
RRAn        26
PosN        19
RRAe        10
PosA         8
RRNn         5
RRNe         2
Name: count, dtype: int64

In [175]:
#Check the datatype of first 40 columns
df.dtypes.head(40)

MSSubClass        int64
MSZoning         object
LotFrontage     float64
LotArea           int64
Street           object
LotShape         object
LandContour      object
Utilities        object
LotConfig        object
LandSlope        object
Neighborhood     object
Condition1       object
Condition2       object
BldgType         object
HouseStyle       object
OverallQual       int64
OverallCond       int64
YearBuilt         int64
YearRemodAdd      int64
RoofStyle        object
RoofMatl         object
Exterior1st      object
Exterior2nd      object
MasVnrArea      float64
ExterQual        object
ExterCond        object
Foundation       object
BsmtQual         object
BsmtCond         object
BsmtExposure     object
BsmtFinType1     object
BsmtFinSF1        int64
BsmtFinType2     object
BsmtFinSF2        int64
BsmtUnfSF         int64
TotalBsmtSF       int64
Heating          object
HeatingQC        object
CentralAir       object
Electrical       object
dtype: object

In [177]:
#convert all object type columns data to numerical data at once

df[df.select_dtypes(['object']).columns]=df.select_dtypes(['object']).apply(lambda x: pd.factorize(x)[0])
print(df)

      MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  \
0             60         0         65.0     8450       0         0
1             20         0         80.0     9600       0         0
2             60         0         68.0    11250       0         1
3             70         0         60.0     9550       0         1
4             60         0         84.0    14260       0         1
...          ...       ...          ...      ...     ...       ...
1455          60         0         62.0     7917       0         0
1456          20         0         85.0    13175       0         0
1457          70         0         66.0     9042       0         0
1458          20         0         68.0     9717       0         0
1459          20         0         75.0     9937       0         0

      LandContour  Utilities  LotConfig  LandSlope  ...  EnclosedPorch  \
0               0          0          0          0  ...              0
1               0          0          1          0  ...              0
2               0          0          0          0  ...              0
3               0          0          2          0  ...            272
4               0          0          1          0  ...              0
...           ...        ...        ...        ...  ...            ...
1455            0          0          0          0  ...              0
1456            0          0          0          0  ...              0
1457            0          0          0          0  ...              0
1458            0          0          0          0  ...            112
1459            0          0          0          0  ...              0

      3SsnPorch  ScreenPorch  PoolArea  MiscVal  MoSold  YrSold  SaleType  \
0             0            0         0        0       2    2008         0
1             0            0         0        0       5    2007         0
2             0            0         0        0       9    2008         0
3             0            0         0        0       2    2006         0
4             0            0         0        0      12    2008         0
...         ...          ...       ...      ...     ...     ...       ...
1455          0            0         0        0       8    2007         0
1456          0            0         0        0       2    2010         0
1457          0            0         0     2500       5    2010         0
1458          0            0         0        0       4    2010         0
1459          0            0         0        0       6    2008         0

      SaleCondition  SalePrice
0                 0     208500
1                 0     181500
2                 0     223500
3                 1     140000
4                 0     250000
...             ...        ...
1455              0     175000
1456              0     210000
1457              0     266500
1458              0     142125
1459              0     147500

[1346 rows x 74 columns]

In [179]:
df.dtypes.tail(40)

BsmtUnfSF          int64
TotalBsmtSF        int64
Heating            int64
HeatingQC          int64
CentralAir         int64
Electrical         int64
1stFlrSF           int64
2ndFlrSF           int64
LowQualFinSF       int64
GrLivArea          int64
BsmtFullBath       int64
BsmtHalfBath       int64
FullBath           int64
HalfBath           int64
BedroomAbvGr       int64
KitchenAbvGr       int64
KitchenQual        int64
TotRmsAbvGrd       int64
Functional         int64
Fireplaces         int64
GarageType         int64
GarageYrBlt      float64
GarageFinish       int64
GarageCars         int64
GarageArea         int64
GarageQual         int64
GarageCond         int64
PavedDrive         int64
WoodDeckSF         int64
OpenPorchSF        int64
EnclosedPorch      int64
3SsnPorch          int64
ScreenPorch        int64
PoolArea           int64
MiscVal            int64
MoSold             int64
YrSold             int64
SaleType           int64
SaleCondition      int64
SalePrice          int64
dtype: object

In [181]:
df.shape

(1346, 74)